import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/auth";
import { pool } from "@/lib/db";

export const runtime = "nodejs";

function newId(): string {
  const buf = crypto.getRandomValues(new Uint8Array(9));
  return "wp_" + Array.from(buf, (b) => b.toString(16).padStart(2, "0")).join("");
}

function normalizeSite(input: string): string | null {
  const t = (input || "").trim().replace(/\/+$/, "");
  if (!t) return null;
  const withScheme = /^https?:\/\//i.test(t) ? t : `https://${t}`;
  try {
    const u = new URL(withScheme);
    return `${u.protocol}//${u.host}`;
  } catch { return null; }
}

interface PingResponse {
  ok?: boolean;
  plugin_version?: string;
  site_name?: string;
  site_url?: string;
  wp_version?: string;
}

/**
 * POST /api/blogger/connect — body { site_url, api_key }
 * Pings the user's WordPress site through the plugin, saves the
 * connection if the ping succeeds.
 */
export async function POST(req: NextRequest) {
  const session = await auth();
  const userId = Number((session?.user as { id?: string | number } | undefined)?.id);
  if (!session?.user || !Number.isFinite(userId)) {
    return NextResponse.json({ error: "Sign in required" }, { status: 401 });
  }

  let body: { site_url?: string; api_key?: string } = {};
  try { body = await req.json(); } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const siteUrl = normalizeSite(body.site_url || "");
  const apiKey = (body.api_key || "").trim();
  if (!siteUrl) return NextResponse.json({ error: "Enter a valid site URL" }, { status: 400 });
  if (!apiKey || apiKey.length < 24) {
    return NextResponse.json({ error: "API key looks too short — generate one in Settings → Prodlyft Publisher" }, { status: 400 });
  }

  // Probe the plugin.
  let ping: PingResponse | null = null;
  try {
    const r = await fetch(`${siteUrl}/wp-json/prodlyft/v1/ping`, {
      headers: {
        "X-Prodlyft-Key": apiKey,
        "Accept": "application/json",
        // Browser UA — gets us past sites that block requests without
        // one (some LiteSpeed / Cloudflare configs do this on top of
        // their reCAPTCHA check). Real reCAPTCHA challenges still
        // block us; we detect those further down with a friendlier
        // error than "<!DOCTYPE… is not valid JSON".
        "User-Agent": "Mozilla/5.0 (compatible; ProdlyftBlogger/1.0; +https://prodlyft.com)",
      },
      signal: AbortSignal.timeout(15_000),
    });
    if (r.status === 401 || r.status === 403) {
      return NextResponse.json(
        { error: "API key was rejected by your site." },
        { status: 401 },
      );
    }
    if (r.status === 404) {
      return NextResponse.json(
        { error: "The Prodlyft Publisher plugin doesn't seem active on this site (no /wp-json/prodlyft/v1/ endpoint). Install + activate the plugin, then try again." },
        { status: 404 },
      );
    }
    if (!r.ok) {
      return NextResponse.json({ error: `Site responded HTTP ${r.status}` }, { status: 502 });
    }
    // Anti-bot pages return HTTP 200 with text/html (LiteSpeed bot
    // verification, Cloudflare's "Just a moment…", Sucuri firewall,
    // etc.). Detect those before we hand the body to JSON.parse so
    // the user gets a fix-this-on-your-host message instead of the
    // cryptic JSON syntax error.
    const ct = (r.headers.get("content-type") || "").toLowerCase();
    if (!ct.includes("application/json") && !ct.includes("application/ld+json")) {
      const bodyPreview = (await r.text()).slice(0, 2000).toLowerCase();
      const matchers: [RegExp, string][] = [
        [/bot[\s_-]*verification|lsrecaptcha|litespeed.*captcha/i,
          "Your site's LiteSpeed bot-protection / reCAPTCHA challenge is blocking our plugin ping. Whitelist the path /wp-json/* in LiteSpeed Cache → CDN → QUIC.cloud (or temporarily disable bot challenge), reconnect, then re-enable."],
        [/cloudflare|just a moment\.\.\.|checking your browser/i,
          "Cloudflare is challenging our request (probably 'Under Attack Mode' or Bot Fight Mode). Whitelist /wp-json/* in your Cloudflare WAF rules and try again."],
        [/sucuri|access denied/i,
          "Sucuri firewall is blocking the REST request. Allowlist Prodlyft (or whitelist /wp-json/*) in Sucuri → Firewall → Access Control, then try again."],
        [/wordfence|generated by wordfence/i,
          "Wordfence is blocking the REST request. Whitelist Prodlyft or disable Wordfence's 'Block fake Google crawlers' option for /wp-json/*, then try again."],
        [/<!doctype|<html/i,
          "Your site returned an HTML page instead of JSON for the REST endpoint. This usually means WordPress permalinks aren't using a permalink structure (Settings → Permalinks → pick Post name or anything but Plain), or a security plugin / caching layer is rewriting the response."],
      ];
      for (const [pat, msg] of matchers) {
        if (pat.test(bodyPreview)) {
          return NextResponse.json({ error: msg }, { status: 502 });
        }
      }
      // Fallback when we got HTML but couldn't identify the cause.
      return NextResponse.json(
        { error: `Site replied with ${ct || "an unexpected content type"} instead of JSON. This is usually a caching layer or security plugin intercepting REST requests. Check that /wp-json/prodlyft/v1/ping is reachable in your browser while logged in.` },
        { status: 502 },
      );
    }
    try {
      ping = (await r.json()) as PingResponse;
    } catch {
      return NextResponse.json(
        { error: "Plugin returned a malformed response. Make sure you have the latest Prodlyft Publisher plugin installed." },
        { status: 502 },
      );
    }
    if (!ping.ok) {
      return NextResponse.json({ error: "Plugin replied without OK status." }, { status: 502 });
    }
  } catch (e) {
    return NextResponse.json({ error: `Couldn't reach the site: ${(e as Error).message}` }, { status: 502 });
  }

  // Upsert. One user can have many sites; multiple users could in theory all
  // connect to the same site (e.g. an agency). We key by (user_id, site_url).
  const existing = await pool.query<{ id: string }>(
    "SELECT id FROM wp_connections WHERE user_id = $1 AND site_url = $2",
    [userId, siteUrl],
  );
  let id: string;
  if (existing.rowCount && existing.rows[0]?.id) {
    id = existing.rows[0].id;
    await pool.query(
      `UPDATE wp_connections
       SET api_key = $1, site_name = $2, wp_version = $3,
           status = 'active', last_ping_at = NOW(), updated_at = NOW()
       WHERE id = $4`,
      [apiKey, ping.site_name ?? null, ping.wp_version ?? null, id],
    );
  } else {
    id = newId();
    await pool.query(
      `INSERT INTO wp_connections
        (id, user_id, site_url, site_name, api_key, wp_version, status, last_ping_at)
       VALUES ($1, $2, $3, $4, $5, $6, 'active', NOW())`,
      [id, userId, siteUrl, ping.site_name ?? null, apiKey, ping.wp_version ?? null],
    );
  }

  return NextResponse.json({
    id,
    site_url: siteUrl,
    site_name: ping.site_name ?? null,
    wp_version: ping.wp_version ?? null,
  });
}
